version: "3.3"

services:
  server:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:3000"
    volumes:
      - ./data/server_logs:/logs
      - ./coverage:/app/coverage
    environment:
      - MONGO=mongo:27017
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
volumes:
  mongoData: {}